# role: jomrr.resolved
# file: molecule/resources/playbooks/verify.yml
# code: language=ansible-jinja

- name: "PLAYBOOK | Verify"
  hosts: all
  become: false
  gather_facts: false
  tasks:
    - name: "Check if systemd-resolved is running"
      ansible.builtin.systemd:
        name: systemd-resolved
        state: started
      check_mode: true
      register: result
      failed_when: result is changed or result is failed

    - name: "Check if systemd-resolved is enabled"
      ansible.builtin.systemd:
        name: systemd-resolved
        enabled: true
      check_mode: true
      register: result
      failed_when: result is changed or result is failed
